### ISSUE TITLE
get_assignments of train data

### ISSUE THREAD

**Issue by shimon166** [mhahsler/stream#13]
There is any way to get assignments of trained data after executing update()? I don't think using get_assignment() with the same data is the proper way to do it because those point already clustered.
get_clustering_assignment() method does not work for all algorithms

**Comment by mhahsler** [comment]
get_assignment() with the same data will approximately work if you are talking for a model that was trained with lots of data and your update had only relatively few points (i.e., the model was not changed significantly by the update). Unfortunately, most algorithms do not return cluster assignments after clustering. Only DSC_DBSTREAM does that (see get_cluster_assignments()).

get_cluster_assignment(): Please provide a list of which algorithms should support the method, but don't.  Add some code to show the problem.

Thanks,
Michael

**Comment by shimon166** [comment]
Thanks, Actually as a result I want to measure the training set clustering quality of each clustering algorithm (DBStream, Dstream, Denstream, Clustream etc...) so i want to execute update() only once and get the clustering of each training sample as a result. get assignment with the training data return slightly different results when i compared with get_cluster_assignment() results. Unfortunately, As you mentioned get_cluster_assignment() works only for DSC_DBSTREAM.
There is any other alternative to measure ARI of training set data?

**Comment by mhahsler** [comment]
I am not sure how useful it is to measure ARI on the training set during training since the clustering changes. `evaluate` in `stream` implements the common methods to evaluate clustering during learning. Have you looked into that function?

**Comment by shimon166** [comment]
Yes, I looked on the evaluate methods.
I have one more question:
`get_assignments()` in DBStream will stream the data and will change MC's or just retrieve assignments of those points?

**Comment by mhahsler** [comment]
The original clustering is not modified when you use `get_assignment()`. I will update the manual page to state this more clearly.
