### ISSUE TITLE
Pointers regarding evoStream speed

### ISSUE THREAD

**Issue by dinarior** [mhahsler/stream#16]
Hello,

First of all, great package (and documentation)! went from 0 in R to producing results with it in less than an hour.

I am comparing several stream clustering algorithms, specifically, I am currently working on a Gaussian (K=20) dataset of 1mil 2D points, in 1000 batches of size 1000.
Running DBStream for example, I can get results in less than 5 seconds, which is quite impressive.
However, evoStream, while producing better results, is incredibly slow. I have reduced the reclusterGenerations to 10, and populationSize to 5, however, the same dataset took me 956 seconds.

Do you have any pointers for increasing the inference speed? I understand evoStream is more geared for slower streams, however, any improvement would be useful.

Thanks,

Or

**Comment by mhahsler** [comment]
Hi, this is a question for the author of the code for evoStream:
Matthias Carnein <email: Matthias.Carnein@uni-muenster.de>

**Comment by dinarior** [comment]
Thanks!
