### ISSUE TITLE
DSD_Wrapper Function Issue 

### ISSUE THREAD

**Issue by YashSunidhi** [mhahsler/stream#2]
HI 
Could you please help me with some of the missing function like DSD_Wrapper, cluster etc. in stream library, With current version (1.2-2) of Library , I am not having these function. Do we have replacement of this??

Regards
Suyash

**Comment by mhahsler** [comment]
Have a look at [NEWS.md](https://github.com/mhahsler/stream/blob/master/NEWS.md).

"DSC_Memory replaces DSD_Wrapper"
