### ISSUE TITLE
Plotting and evaluating unlabelled data from CSV

### ISSUE THREAD

**Issue by MatthiasCarnein** [mhahsler/stream#4]
It is not possible to plot clusters or evaluate unlabelled data from a `DSD_ReadCSV()` source. This appears to be a bug since doing the same from `DSD_Memory()` is working just fine. 

Consider the following example where an unlabeled csv is created, read and then plotted:

```
## create csv
library(stream)
write_stream(DSD_Gaussians(k = 3, d = 2), "data.csv", n = 1000, class = F)

## read csv, plot and evaluate
stream <- DSD_ReadCSV("data.csv")
dstream <- DSC_DStream(gridsize = .01)
update(dstream, stream, n = 500)
plot(dstream, stream, type="micro") ## Error
evaluate(dstream, stream, n=200, measure = c("numMicroClusters")) ## Error

# Error in get_points.DSD_ReadCSV(dsd, n, cluster = TRUE) :
#   Stream does not support class/cluster labels.

## cleanup
close_stream(stream)
file.remove("data.csv")
```

The problem occurs in the `get_points.DSD_ReadCSV()` method which yields an error if no class label exists: 
```
if((class || cluster) && is.null(x$class)) 
   stop("Stream does not support class/cluster labels.")
```

Simply removing the stop condition fixes the issue. However, I'm not sure whether this introduces undesired side effects.

**Comment by mhahsler** [comment]
Thanks for the detailed bug report. I have fixed the problem now in the development version on GitHub. The bugfix will be released on CRAN with the next release (not quite sure when that will be).
