### ISSUE TITLE
fyi - examples don't work on stream_1.2-4 with no DSD_Wrapper

### ISSUE THREAD

**Issue by mik3hall** [mhahsler/stream#8]
> mydatastream <- DSD_FFDFstream(x = myffdf, k = 100, loop=TRUE) 
> get_points(mydatastream, n=5)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'get_points.DSD_Wrapper' not found

and

> dsd <- DSD_Gaussians(k=3, d=2)
> replayer <- DSD_Wrapper(dsd, k=3, n=1000)
Error in DSD_Wrapper(dsd, k = 3, n = 1000) : 
  could not find function "DSD_Wrapper"

I think for what I want to look at I can manage without DSD_Wrapper. But I thought I'd mention that a number of examples I came across, and others might come across, in searching on this do seem to require it.

**Comment by mhahsler** [comment]
Hi! DSD_Wapper was replaced by DSD_Memory in 2014. It should be straightforward to fix your code. Hope this helps!
